DELETE FROM TS_STATUS;

INSERT INTO TS_STATUS (STATUS_ID,STATUS_SELITE,READONLY) VALUES ('1','Hyväksymisesitys saapunut, ei käsittelyssä','0');
INSERT INTO TS_STATUS (STATUS_ID,STATUS_SELITE,READONLY) VALUES ('2','Hyväksymisesitys käsittelyssä','0');
INSERT INTO TS_STATUS (STATUS_ID,STATUS_SELITE,READONLY) VALUES ('3','Hyväksymispäätös annettu / odottaa kuulutustod., lainv.päätöstä tms.','0');
INSERT INTO TS_STATUS (STATUS_ID,STATUS_SELITE,READONLY) VALUES ('4','Hyväksymispäätös annettu, lainvoimainen','0');
INSERT INTO TS_STATUS (STATUS_ID,STATUS_SELITE,READONLY) VALUES ('5','Luovutettu liikenteelle osittain','0');
INSERT INTO TS_STATUS (STATUS_ID,STATUS_SELITE,READONLY) VALUES ('6','Luovutettu liikenteelle kokonaan','0');
INSERT INTO TS_STATUS (STATUS_ID,STATUS_SELITE,READONLY) VALUES ('7','Valitus','0');
INSERT INTO TS_STATUS (STATUS_ID,STATUS_SELITE,READONLY) VALUES ('8','LVM:n hyväksymispäätös','0');
INSERT INTO TS_STATUS (STATUS_ID,STATUS_SELITE,READONLY) VALUES ('9','Rauennut','0');
INSERT INTO TS_STATUS (STATUS_ID,STATUS_SELITE,READONLY) VALUES ('10','Ei statusta','1');
INSERT INTO TS_STATUS (STATUS_ID,STATUS_SELITE,READONLY) VALUES ('11','Palautettu ELYlle','0');


INSERT INTO YS_STATUS (STATUS_ID, SELITE, READONLY) VALUES (8, 'Rauennut', 0);