-- TKYP-161: Tiesu-kenttien muutokset

-- Backup tables
-- CREATE TABLE TIESUUNNITELMA_15102020 AS SELECT * FROM TIESUUNNITELMA;
-- CREATE TABLE YLEISSUUNITELMA_15102020 AS SELECT * FROM YLEISSUUNITELMA;
-- CREATE TABLE RATASUUNNITELMA_15102020 AS SELECT * FROM RATASUUNNITELMA;
-- CREATE TABLE RAUTATIEN_YLEISSUUNN_15102020 AS SELECT * FROM RAUTATIEN_YLEISSUUNNITELMA;
-- CREATE TABLE TIESUUNNITELMAHIST_15102020 AS SELECT * FROM TIESUUNNITELMAHISTORIA;
-- CREATE TABLE YLEISSUUNNITELMAHIST_15102020 AS SELECT * FROM YLEISSUUNNITELMAHISTORIA;
-- CREATE TABLE RT_HISTORIA_15102020 AS SELECT * FROM RT_HISTORIA;
-- CREATE TABLE RYS_HISTORIA_15102020 AS SELECT * FROM RYS_HISTORIA;



-- Add date columns
ALTER TABLE TIESUUNNITELMA ADD LAINVOIMAISUUS_DATE DATE;
ALTER TABLE TIESUUNNITELMA ADD OSAPAATOS_ANNETTU_DATE DATE;
ALTER TABLE TIESUUNNITELMA ADD LIIKENTEESEENLUOVUTUS_OSA_DATE DATE;
ALTER TABLE TIESUUNNITELMA ADD LIIKENTEESEENLUOVUTUS_KOKO_DAT DATE;
ALTER TABLE YLEISSUUNITELMA ADD LAINVOIMAISUUS_DATE DATE;
ALTER TABLE YLEISSUUNITELMA ADD OSAPAATOS_ANNETTU_DATE DATE;
ALTER TABLE RATASUUNNITELMA ADD LAINVOIMAISUUS_DATE DATE;
ALTER TABLE RATASUUNNITELMA ADD OSAPAATOS_ANNETTU_DATE DATE;
ALTER TABLE RAUTATIEN_YLEISSUUNNITELMA ADD LAINVOIMAISUUS_DATE DATE;
ALTER TABLE RAUTATIEN_YLEISSUUNNITELMA ADD OSAPAATOS_ANNETTU_DATE DATE;

ALTER TABLE TIESUUNNITELMAHISTORIA ADD LAINVOIMAISUUS_DATE DATE;
ALTER TABLE TIESUUNNITELMAHISTORIA ADD OSAPAATOS_ANNETTU_DATE DATE;
ALTER TABLE TIESUUNNITELMAHISTORIA ADD LIIKENTEESEENLUOVUTUS_OSA_DATE DATE;
ALTER TABLE TIESUUNNITELMAHISTORIA ADD LIIKENTEESEENLUOVUTUS_KOKO_DAT DATE;
ALTER TABLE YLEISSUUNNITELMAHISTORIA ADD LAINVOIMAISUUS_DATE DATE;
ALTER TABLE YLEISSUUNNITELMAHISTORIA ADD OSAPAATOS_ANNETTU_DATE DATE;
ALTER TABLE RT_HISTORIA ADD LAINVOIMAISUUS_DATE DATE;
ALTER TABLE RT_HISTORIA ADD OSAPAATOS_ANNETTU_DATE DATE;
ALTER TABLE RYS_HISTORIA ADD LAINVOIMAISUUS_DATE DATE;
ALTER TABLE RYS_HISTORIA ADD OSAPAATOS_ANNETTU_DATE DATE;



-- Attempt to convert data to date values
-- NOTE: This process is based on the test and production databases as of 15.10.2020

-- Special fixes
UPDATE TIESUUNNITELMA SET LAINVOIMAISUUS = '14.2.2017' WHERE LAINVOIMAISUUS = '14.2.20107';
UPDATE TIESUUNNITELMA SET LAINVOIMAISUUS = '27.2.2006' WHERE LAINVOIMAISUUS = '27.2.2006.';

-- lainvoimaisuus: convert values of format dd.mm.yyyy to dates, remove other text values such as 'odottaa'
UPDATE TIESUUNNITELMA SET LAINVOIMAISUUS_DATE = CASE WHEN trim(TRANSLATE(LAINVOIMAISUUS, '0123456789.', ' ')) IS NULL THEN to_date(LAINVOIMAISUUS, 'dd.mm.yyyy') END;
UPDATE YLEISSUUNITELMA SET LAINVOIMAISUUS_DATE = CASE WHEN trim(TRANSLATE(LAINVOIMAISUUS, '0123456789.', ' ')) IS NULL THEN to_date(LAINVOIMAISUUS, 'dd.mm.yyyy') END;
UPDATE RATASUUNNITELMA SET LAINVOIMAISUUS_DATE = CASE WHEN trim(TRANSLATE(LAINVOIMAISUUS, '0123456789.', ' ')) IS NULL THEN to_date(LAINVOIMAISUUS, 'dd.mm.yyyy') END;
UPDATE RAUTATIEN_YLEISSUUNNITELMA SET LAINVOIMAISUUS_DATE = CASE WHEN trim(TRANSLATE(LAINVOIMAISUUS, '0123456789.', ' ')) IS NULL THEN to_date(LAINVOIMAISUUS, 'dd.mm.yyyy') END;

UPDATE TIESUUNNITELMAHISTORIA SET LAINVOIMAISUUS_DATE = CASE WHEN trim(TRANSLATE(LAINVOIMAISUUS, '0123456789.', ' ')) IS NULL THEN to_date(LAINVOIMAISUUS, 'dd.mm.yyyy') END;
UPDATE YLEISSUUNNITELMAHISTORIA SET LAINVOIMAISUUS_DATE = CASE WHEN trim(TRANSLATE(LAINVOIMAISUUS, '0123456789.', ' ')) IS NULL THEN to_date(LAINVOIMAISUUS, 'dd.mm.yyyy') END;
UPDATE RT_HISTORIA SET LAINVOIMAISUUS_DATE = CASE WHEN trim(TRANSLATE(LAINVOIMAISUUS, '0123456789.', ' ')) IS NULL THEN to_date(LAINVOIMAISUUS, 'dd.mm.yyyy') END;
UPDATE RYS_HISTORIA SET LAINVOIMAISUUS_DATE = CASE WHEN trim(TRANSLATE(LAINVOIMAISUUS, '0123456789.', ' ')) IS NULL THEN to_date(LAINVOIMAISUUS, 'dd.mm.yyyy') END;

-- osapaatos_annettu: convert values of format dd-mon-yy to dates, except in tiesuunnitelma tables which are already of type date for this column
-- UPDATE TIESUUNNITELMA SET OSAPAATOS_ANNETTU_DATE = CASE WHEN trim(TRANSLATE(OSAPAATOS_ANNETTU, '0123456789.', ' ')) IS NOT NULL THEN to_date(OSAPAATOS_ANNETTU, 'dd-mon-yy') END;
UPDATE TIESUUNNITELMA SET OSAPAATOS_ANNETTU_DATE = OSAPAATOS_ANNETTU;
UPDATE YLEISSUUNITELMA SET OSAPAATOS_ANNETTU_DATE = CASE WHEN trim(TRANSLATE(OSAPAATOS_ANNETTU, '0123456789.', ' ')) IS NOT NULL THEN to_date(OSAPAATOS_ANNETTU, 'dd-mon-yy') END;
UPDATE RATASUUNNITELMA SET OSAPAATOS_ANNETTU_DATE = CASE WHEN trim(TRANSLATE(OSAPAATOS_ANNETTU, '0123456789.', ' ')) IS NOT NULL THEN to_date(OSAPAATOS_ANNETTU, 'dd-mon-yy') END;
UPDATE RAUTATIEN_YLEISSUUNNITELMA SET OSAPAATOS_ANNETTU_DATE = CASE WHEN trim(TRANSLATE(OSAPAATOS_ANNETTU, '0123456789.', ' ')) IS NOT NULL THEN to_date(OSAPAATOS_ANNETTU, 'dd-mon-yy') END;

-- UPDATE TIESUUNNITELMAHISTORIA SET OSAPAATOS_ANNETTU_DATE = CASE WHEN trim(TRANSLATE(OSAPAATOS_ANNETTU, '0123456789.', ' ')) IS NOT NULL THEN to_date(OSAPAATOS_ANNETTU, 'dd-mon-yy') END;
UPDATE TIESUUNNITELMAHISTORIA SET OSAPAATOS_ANNETTU_DATE = OSAPAATOS_ANNETTU;
UPDATE YLEISSUUNNITELMAHISTORIA SET OSAPAATOS_ANNETTU_DATE = CASE WHEN trim(TRANSLATE(OSAPAATOS_ANNETTU, '0123456789.', ' ')) IS NOT NULL THEN to_date(OSAPAATOS_ANNETTU, 'dd-mon-yy') END;
UPDATE RT_HISTORIA SET OSAPAATOS_ANNETTU_DATE = CASE WHEN trim(TRANSLATE(OSAPAATOS_ANNETTU, '0123456789.', ' ')) IS NOT NULL THEN to_date(OSAPAATOS_ANNETTU, 'dd-mon-yy') END;
UPDATE RYS_HISTORIA SET OSAPAATOS_ANNETTU_DATE = CASE WHEN trim(TRANSLATE(OSAPAATOS_ANNETTU, '0123456789.', ' ')) IS NOT NULL THEN to_date(OSAPAATOS_ANNETTU, 'dd-mon-yy') END;

-- liikenteeseenluovutus_osa: convert values of format dd.mm.yyyy to dates, convert values starting with a year to 01.01.yyyy, so for example '2017 ja 2018' becomes '01.01.2017'
UPDATE TIESUUNNITELMA SET LIIKENTEESEENLUOVUTUS_OSA_DATE = CASE 
  WHEN LIIKENTEESEENLUOVUTUS_OSA IS NULL THEN NULL
  WHEN trim(TRANSLATE(substr(LIIKENTEESEENLUOVUTUS_OSA, 1, 4), '0123456789', ' ')) IS NULL THEN to_date('01.01.' || substr(LIIKENTEESEENLUOVUTUS_OSA, 1, 4), 'dd.mm.yyyy')
  WHEN trim(TRANSLATE(LIIKENTEESEENLUOVUTUS_OSA, '0123456789.', ' ')) IS NULL THEN to_date(LIIKENTEESEENLUOVUTUS_OSA, 'dd.mm.yyyy')
END;

UPDATE TIESUUNNITELMAHISTORIA SET LIIKENTEESEENLUOVUTUS_OSA_DATE = CASE 
  WHEN LIIKENTEESEENLUOVUTUS_OSA IS NULL THEN NULL
  WHEN trim(TRANSLATE(substr(LIIKENTEESEENLUOVUTUS_OSA, 1, 4), '0123456789', ' ')) IS NULL THEN to_date('01.01.' || substr(LIIKENTEESEENLUOVUTUS_OSA, 1, 4), 'dd.mm.yyyy')
  WHEN trim(TRANSLATE(LIIKENTEESEENLUOVUTUS_OSA, '0123456789.', ' ')) IS NULL THEN to_date(LIIKENTEESEENLUOVUTUS_OSA, 'dd.mm.yyyy')
END;

-- liikenteeseenluovutus_koko: convert values of format dd.mm.yyyy to dates, convert values starting with a year to 01.01.yyyy, so for example '2011 hall.muut.' becomes '01.01.2011'
UPDATE TIESUUNNITELMA SET LIIKENTEESEENLUOVUTUS_KOKO_DAT = CASE 
  WHEN LIIKENTEESEENLUOVUTUS_KOKO IS NULL THEN NULL
  WHEN trim(TRANSLATE(substr(LIIKENTEESEENLUOVUTUS_KOKO, 1, 4), '0123456789', ' ')) IS NULL THEN to_date('01.01.' || substr(LIIKENTEESEENLUOVUTUS_KOKO, 1, 4), 'dd.mm.yyyy')
  WHEN trim(TRANSLATE(LIIKENTEESEENLUOVUTUS_KOKO, '0123456789.', ' ')) IS NULL THEN to_date(LIIKENTEESEENLUOVUTUS_KOKO, 'dd.mm.yyyy')
END;

UPDATE TIESUUNNITELMAHISTORIA SET LIIKENTEESEENLUOVUTUS_KOKO_DAT = CASE 
  WHEN LIIKENTEESEENLUOVUTUS_KOKO IS NULL THEN NULL
  WHEN trim(TRANSLATE(substr(LIIKENTEESEENLUOVUTUS_KOKO, 1, 4), '0123456789', ' ')) IS NULL THEN to_date('01.01.' || substr(LIIKENTEESEENLUOVUTUS_KOKO, 1, 4), 'dd.mm.yyyy')
  WHEN trim(TRANSLATE(LIIKENTEESEENLUOVUTUS_KOKO, '0123456789.', ' ')) IS NULL THEN to_date(LIIKENTEESEENLUOVUTUS_KOKO, 'dd.mm.yyyy')
END;



-- Rename text columns to have prefix _old
ALTER TABLE TIESUUNNITELMA RENAME COLUMN LAINVOIMAISUUS TO OLD_LAINVOIMAISUUS;
ALTER TABLE TIESUUNNITELMA RENAME COLUMN OSAPAATOS_ANNETTU TO OLD_OSAPAATOS_ANNETTU;
ALTER TABLE TIESUUNNITELMA RENAME COLUMN LIIKENTEESEENLUOVUTUS_OSA TO OLD_LIIKENTEESEENLUOVUTUS_OSA;
ALTER TABLE TIESUUNNITELMA RENAME COLUMN LIIKENTEESEENLUOVUTUS_KOKO TO OLD_LIIKENTEESEENLUOVUTUS_KOKO;
ALTER TABLE YLEISSUUNITELMA RENAME COLUMN LAINVOIMAISUUS TO OLD_LAINVOIMAISUUS;
ALTER TABLE YLEISSUUNITELMA RENAME COLUMN OSAPAATOS_ANNETTU TO OLD_OSAPAATOS_ANNETTU;
ALTER TABLE RATASUUNNITELMA RENAME COLUMN LAINVOIMAISUUS TO OLD_LAINVOIMAISUUS;
ALTER TABLE RATASUUNNITELMA RENAME COLUMN OSAPAATOS_ANNETTU TO OLD_OSAPAATOS_ANNETTU;
ALTER TABLE RAUTATIEN_YLEISSUUNNITELMA RENAME COLUMN LAINVOIMAISUUS TO OLD_LAINVOIMAISUUS;
ALTER TABLE RAUTATIEN_YLEISSUUNNITELMA RENAME COLUMN OSAPAATOS_ANNETTU TO OLD_OSAPAATOS_ANNETTU;

ALTER TABLE TIESUUNNITELMAHISTORIA RENAME COLUMN LAINVOIMAISUUS TO OLD_LAINVOIMAISUUS;
ALTER TABLE TIESUUNNITELMAHISTORIA RENAME COLUMN OSAPAATOS_ANNETTU TO OLD_OSAPAATOS_ANNETTU;
ALTER TABLE TIESUUNNITELMAHISTORIA RENAME COLUMN LIIKENTEESEENLUOVUTUS_OSA TO OLD_LIIKENTEESEENLUOVUTUS_OSA;
ALTER TABLE TIESUUNNITELMAHISTORIA RENAME COLUMN LIIKENTEESEENLUOVUTUS_KOKO TO OLD_LIIKENTEESEENLUOVUTUS_KOKO;
ALTER TABLE YLEISSUUNNITELMAHISTORIA RENAME COLUMN LAINVOIMAISUUS TO OLD_LAINVOIMAISUUS;
ALTER TABLE YLEISSUUNNITELMAHISTORIA RENAME COLUMN OSAPAATOS_ANNETTU TO OLD_OSAPAATOS_ANNETTU;
ALTER TABLE RT_HISTORIA RENAME COLUMN LAINVOIMAISUUS TO OLD_LAINVOIMAISUUS;
ALTER TABLE RT_HISTORIA RENAME COLUMN OSAPAATOS_ANNETTU TO OLD_OSAPAATOS_ANNETTU;
ALTER TABLE RYS_HISTORIA RENAME COLUMN LAINVOIMAISUUS TO OLD_LAINVOIMAISUUS;
ALTER TABLE RYS_HISTORIA RENAME COLUMN OSAPAATOS_ANNETTU TO OLD_OSAPAATOS_ANNETTU;



-- Rename date columns to original column names
ALTER TABLE TIESUUNNITELMA RENAME COLUMN LAINVOIMAISUUS_DATE TO LAINVOIMAISUUS;
ALTER TABLE TIESUUNNITELMA RENAME COLUMN OSAPAATOS_ANNETTU_DATE TO OSAPAATOS_ANNETTU;
ALTER TABLE TIESUUNNITELMA RENAME COLUMN LIIKENTEESEENLUOVUTUS_OSA_DATE TO LIIKENTEESEENLUOVUTUS_OSA;
ALTER TABLE TIESUUNNITELMA RENAME COLUMN LIIKENTEESEENLUOVUTUS_KOKO_DAT TO LIIKENTEESEENLUOVUTUS_KOKO;
ALTER TABLE YLEISSUUNITELMA RENAME COLUMN LAINVOIMAISUUS_DATE TO LAINVOIMAISUUS;
ALTER TABLE YLEISSUUNITELMA RENAME COLUMN OSAPAATOS_ANNETTU_DATE TO OSAPAATOS_ANNETTU;
ALTER TABLE RATASUUNNITELMA RENAME COLUMN LAINVOIMAISUUS_DATE TO LAINVOIMAISUUS;
ALTER TABLE RATASUUNNITELMA RENAME COLUMN OSAPAATOS_ANNETTU_DATE TO OSAPAATOS_ANNETTU;
ALTER TABLE RAUTATIEN_YLEISSUUNNITELMA RENAME COLUMN LAINVOIMAISUUS_DATE TO LAINVOIMAISUUS;
ALTER TABLE RAUTATIEN_YLEISSUUNNITELMA RENAME COLUMN OSAPAATOS_ANNETTU_DATE TO OSAPAATOS_ANNETTU;

ALTER TABLE TIESUUNNITELMAHISTORIA RENAME COLUMN LAINVOIMAISUUS_DATE TO LAINVOIMAISUUS;
ALTER TABLE TIESUUNNITELMAHISTORIA RENAME COLUMN OSAPAATOS_ANNETTU_DATE TO OSAPAATOS_ANNETTU;
ALTER TABLE TIESUUNNITELMAHISTORIA RENAME COLUMN LIIKENTEESEENLUOVUTUS_OSA_DATE TO LIIKENTEESEENLUOVUTUS_OSA;
ALTER TABLE TIESUUNNITELMAHISTORIA RENAME COLUMN LIIKENTEESEENLUOVUTUS_KOKO_DAT TO LIIKENTEESEENLUOVUTUS_KOKO;
ALTER TABLE YLEISSUUNNITELMAHISTORIA RENAME COLUMN LAINVOIMAISUUS_DATE TO LAINVOIMAISUUS;
ALTER TABLE YLEISSUUNNITELMAHISTORIA RENAME COLUMN OSAPAATOS_ANNETTU_DATE TO OSAPAATOS_ANNETTU;
ALTER TABLE RT_HISTORIA RENAME COLUMN LAINVOIMAISUUS_DATE TO LAINVOIMAISUUS;
ALTER TABLE RT_HISTORIA RENAME COLUMN OSAPAATOS_ANNETTU_DATE TO OSAPAATOS_ANNETTU;
ALTER TABLE RYS_HISTORIA RENAME COLUMN LAINVOIMAISUUS_DATE TO LAINVOIMAISUUS;
ALTER TABLE RYS_HISTORIA RENAME COLUMN OSAPAATOS_ANNETTU_DATE TO OSAPAATOS_ANNETTU;
