--ANALPK-1314

ALTER TABLE "TIESUUNNITELMA" ADD (
    "SISRATASUUNNITTELUA" NUMBER
);

ALTER TABLE "TIESUUNNITELMAHISTORIA" ADD (
    "SISRATASUUNNITTELUA" NUMBER
);

ALTER TABLE "RATASUUNNITELMA" ADD (
    "SISTIESUUNNITTELUA" NUMBER
);

ALTER TABLE "RT_HISTORIA" ADD (
    "SISTIESUUNNITTELUA" NUMBER
);
