-- ANALPK-1316 Uudet päivämääräkentät Ratatoimitus tehty ja Maantietoimitus tehty

ALTER TABLE "RATASUUNNITELMA" ADD (
    "RATATOIMITUSTEHTY" DATE
);
ALTER TABLE "RT_HISTORIA" ADD (
    "RATATOIMITUSTEHTY" DATE
);

ALTER TABLE "TIESUUNNITELMA" ADD (
    "MAANTIETOIMITUSTEHTY" DATE
);

ALTER TABLE "TIESUUNNITELMAHISTORIA" ADD (
    "MAANTIETOIMITUSTEHTY" DATE
);
