services:
  db:
    image: tiesu-pgsql
    build:
      context: .
      dockerfile: ./Dockerfile_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tiesu
      POSTGRES_PASSWORD: tiesu123

  tiesu:
    image: tiesu-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
