ALTER TABLE "YLEISSUUNITELMA" ADD (
	"HAO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE),
	"KHO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE)
);
ALTER TABLE "TIESUUNNITELMA" ADD (
	"HAO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE),
	"KHO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE)
);
ALTER TABLE "RAUTATIEN_YLEISSUUNNITELMA" ADD (
	"HAO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE),
	"KHO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE)
);
ALTER TABLE "RATASUUNNITELMA" ADD (
	"HAO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE),
	"KHO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE)
);