ALTER TABLE "YLEISSUUNNITELMAHISTORIA" ADD (
	"HAO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE),
	"KHO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE)
);
ALTER TABLE "TIESUUNNITELMAHISTORIA" ADD (
	"HAO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE),
	"KHO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE)
);
ALTER TABLE "RYS_HISTORIA" ADD (
	"HAO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE),
	"KHO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE)
);
ALTER TABLE "RT_HISTORIA" ADD (
	"HAO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE),
	"KHO_VALIPAATOS_SISALTO" VARCHAR2(1000 BYTE)
);