ALTER TABLE "RATASUUNNITELMA" ADD (
	"KAYTTOONOTTOLUOVUTUS_OSA" DATE,
	"KAYTTOONOTTOLUOVUTUS_KOKO" DATE
);
ALTER TABLE "RT_HISTORIA" ADD (
	"KAYTTOONOTTOLUOVUTUS_OSA" DATE,
	"KAYTTOONOTTOLUOVUTUS_KOKO" DATE
);