ALTER TABLE "RATASUUNNITELMA" ADD (
	"SAHKO" FLOAT(126),
	"VIESTINTA" FLOAT(126),
	"VESI" FLOAT(126)
);
ALTER TABLE "RT_HISTORIA" ADD (
	"SAHKO" FLOAT(126),
	"VIESTINTA" FLOAT(126),
	"VESI" FLOAT(126)
);

ALTER TABLE "RAUTATIEN_YLEISSUUNNITELMA" ADD (
	"SAHKO" FLOAT(126),
	"VIESTINTA" FLOAT(126),
	"VESI" FLOAT(126)
);
ALTER TABLE "RYS_HISTORIA" ADD (
	"SAHKO" FLOAT(126),
	"VIESTINTA" FLOAT(126),
	"VESI" FLOAT(126)
);