--------------------------------------------------------
--  DDL for Table PALVELUPAIKAT
--------------------------------------------------------
CREATE TABLE "PALVELUPAIKAT"
(
    "NIMI" NVARCHAR2(1000),
    "LYHENNE" NVARCHAR2(100),
    "RATAOSA" NVARCHAR2(1000),
    "TYYPPI" NVARCHAR2(1000),
    "HENKILOLIIKENNE" NVARCHAR2(50),
    "TAVARALIIKENNE" NVARCHAR2(50),
    "KAUKOOHJAUS" NVARCHAR2(50),
    "LIIKENNEPAIKAN_OHITUS" NVARCHAR2(100),
    "LAHTO_MAARA" NVARCHAR2(100),
    "VETURIN_HUOLTOON_STA" NVARCHAR2(100),
    "MANUAALIVAIHDETYO_TARVITAAN" NVARCHAR2(100),
    "RAJOITEVAIHTOKULKUTIENMUODOST" NVARCHAR2(100),
    "RATATYON_TURVAUS" NVARCHAR2(100),
    "URAKOITSIJA_FINRAIL" NVARCHAR2(50),
    "URAKOITSIJA_VR" NVARCHAR2(50),
    "URAKOITSIJA_JOKU_MUU" NVARCHAR2(2000),
    "HUOMAUTUS" NVARCHAR2(2000),
    "LISAMIEHITYKSEN_TILAUS" NVARCHAR2(2000),
    "CREATED" DATE,
    "LAST_MODIFIED_DATE" DATE,
    "LAST_MODIFIED_BY" NVARCHAR2(500),
    "USERNAME" NVARCHAR2(500),
    "FORM_VERSION" NVARCHAR2(50),
    "DOCUMENT_ID" NVARCHAR2(100),
    "DELETED" NVARCHAR2(50),
    "APP" NVARCHAR2(500),
    "FORM" NVARCHAR2(500)
);

CREATE VIEW "PALVELUPAIKAT_LATEST"
(
    "NIMI",
    "LYHENNE",
    "RATAOSA",
    "TYYPPI",
    "HENKILOLIIKENNE",
    "TAVARALIIKENNE",
    "KAUKOOHJAUS",
    "LIIKENNEPAIKAN_OHITUS",
    "LAHTO_MAARA",
    "VETURIN_HUOLTOON_STA",
    "MANUAALIVAIHDETYO_TARVITAAN",
    "RAJOITEVAIHTOKULKUTIENMUODOST",
    "RATATYON_TURVAUS",
    "URAKOITSIJA_FINRAIL",
    "URAKOITSIJA_VR",
    "URAKOITSIJA_JOKU_MUU",
    "HUOMAUTUS",
    "LISAMIEHITYKSEN_TILAUS",
    "CREATED",
    "LAST_MODIFIED_DATE",
    "LAST_MODIFIED_BY",
    "USERNAME",
    "
FORM_VERSION",
    "DOCUMENT_ID",
    "DELETED",
    "APP",
    "FORM",
    "RECENCY"
)
AS
    SELECT "NIMI", "LYHENNE", "RATAOSA", "TYYPPI", "HENKILOLIIKENNE", "TAVARALIIKENNE", "KAUKOOHJAUS", "LIIKENNEPAIKAN_OHITUS", "LAHTO_MAARA", "VETURIN_HUOLTOON_STA", "MANUAALIVAIHDETYO_TARVITAAN", "RAJOITEVAIHTOKULKUTIENMUODOST", "RATATYON_TURVAUS", "URAKOITSIJA_FINRAIL", "URAKOITSIJA_VR", "URAKOITSIJA_JOKU_MUU", "HUOMAUTUS", "LISAMIEHITYKSEN_TILAUS", "CREATED", "LAST_MODIFIED_DATE", "LAST_MODIFIED_BY", "USERNAME", "FORM_VERSION", "DOCUMENT_ID", "DELETED", "APP", "FORM", "RECENCY"
    FROM (SELECT palvelupaikat.*, ROW_NUMBER() OVER (PARTITION BY document_id ORDER BY last_modified_date DESC) AS recency
        FROM palvelupaikat)
    WHERE recency=1 AND Deleted='N';
