--------------------------------------------------------
--  DDL for Table YLEISSUUNITELMA
--------------------------------------------------------

  CREATE TABLE "YLEISSUUNITELMA" 
   (	"YS_WID" NUMBER(*,0), 
	"YLEISSUUNITELMAN_NRO" NUMBER(*,0), 
	"YLEISSUUNNITELMAN_NIMI" VARCHAR2(1000 BYTE), 
	"KASITTELIJA" VARCHAR2(100 BYTE), 
	"SUUNNITELMALAJI" VARCHAR2(500 BYTE), 
	"YLEISSUUNITELMAN_KUVAUS" VARCHAR2(2000 BYTE), 
	"DIAARI" VARCHAR2(60 BYTE), 
	"ELY_KESKUS" VARCHAR2(50 BYTE), 
	"Y_STATUS_ID" NUMBER(*,0), 
	"HYVAKSYTTY_ESITYS_LAADITTU" DATE, 
	"HYVAKSYTTY_ESITYS_SAAPUNUT" DATE, 
	"MUISTUTUKSET" NUMBER(*,0), 
	"HYVAKSYTTY_PAATOS_ANNETTU" DATE, 
	"VALITUSTEN_MAARA" NUMBER(*,0), 
	"SELITYS" VARCHAR2(1000 BYTE), 
	"KASITTELY_VRK" NUMBER(*,0), 
	"OSAPAATOS_ANNETTU" VARCHAR2(500 BYTE), 
	"HAO_PVM" DATE, 
	"HAO_SISALTO" VARCHAR2(1000 BYTE), 
	"KHO_PVM" DATE, 
	"KHO_SISALTO" VARCHAR2(1000 BYTE), 
	"LAINVOIMAISUUS" VARCHAR2(200 BYTE), 
	"LAINVOIMASUUS_PAATTYY" DATE, 
	"RAENNUT" VARCHAR2(1000 BYTE), 
	"TIESUUNNITELMA_LAADITTU" VARCHAR2(1000 BYTE), 
	"JATKOPAATOS" DATE
   );
--------------------------------------------------------
--  Constraints for Table YLEISSUUNITELMA
--------------------------------------------------------

  ALTER TABLE "YLEISSUUNITELMA" ADD PRIMARY KEY ("YS_WID");
  ALTER TABLE "YLEISSUUNITELMA" MODIFY ("DIAARI" NOT NULL ENABLE);
  ALTER TABLE "YLEISSUUNITELMA" MODIFY ("YLEISSUUNNITELMAN_NIMI" NOT NULL ENABLE);
  ALTER TABLE "YLEISSUUNITELMA" MODIFY ("YS_WID" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Sequence YLEISUUNITELMA_SEQ
--------------------------------------------------------

CREATE SEQUENCE "YLEISSUUNITELMA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;
