ALTER TABLE YS_STATUS ADD READONLY NUMBER DEFAULT 0;

UPDATE YS_STATUS SET READONLY=1 WHERE STATUS_ID = -1;
UPDATE YS_STATUS SET READONLY=1 WHERE STATUS_ID = 5;

UPDATE YS_STATUS SET SELITE='Hyväksymisesitys käsittelyssä' WHERE STATUS_ID = 2;
UPDATE YS_STATUS SET SELITE='Hyväksymispäätös annettu / odottaa kuulutustod., lainv. päätöstä' WHERE STATUS_ID = 3;

INSERT INTO YS_STATUS (STATUS_ID, SELITE) VALUES (6,'Hyväksymispäätös annettu, lainvoimainen');
INSERT INTO YS_STATUS (STATUS_ID, SELITE) VALUES (7,'LVM:n hyväksymispäätös');
INSERT INTO YS_STATUS (STATUS_ID, SELITE) VALUES (9,'Palautettu ELYlle');
