CREATE ROLE TIESU_ROLE;
-- Object privileges granted to TIESU_ROLE
CREATE OR REPLACE DIRECTORY COMMON_DATA_PUMP_DIR AS '/opt/oracle/oradata/pump';
GRANT READ, WRITE ON DIRECTORY COMMON_DATA_PUMP_DIR TO TIESU_ROLE;
-- System privileges granted to TIESU_ROLE
GRANT CREATE PROCEDURE TO TIESU_ROLE;
GRANT CREATE SEQUENCE TO TIESU_ROLE;
GRANT CREATE SESSION TO TIESU_ROLE;
GRANT CREATE TABLE TO TIESU_ROLE;
GRANT CREATE TRIGGER TO TIESU_ROLE;
GRANT CREATE TYPE TO TIESU_ROLE;
GRANT CREATE VIEW TO TIESU_ROLE;
CREATE TABLESPACE TIESU_DATA DATAFILE 'tiesu_data1.dbf' SIZE 20M REUSE AUTOEXTEND ON maxsize 5G;
create user tiesu
identified by livirules default tablespace TIESU_DATA quota 4G on TIESU_DATA;
GRANT TIESU_ROLE to tiesu;
ALTER SYSTEM
SET DEFERRED_SEGMENT_CREATION
=FALSE;
