CREATE TABLE "RT_HISTORIA" (
"RIVI_ID" NUMBER NOT NULL,

   	"TUNNUS" NUMBER(*,0), 
   	
	"SUUNNITELMAN_NIMI" VARCHAR2(1000 BYTE), 
	
	"SUUNNITELMAN_KUVAUS" VARCHAR2(2000 BYTE), 
	"YVA_HANKE" NUMBER,
	"ASIANUMERO" VARCHAR2(60 BYTE), 
	"ELY_KESKUS" VARCHAR2(50 BYTE), 
	"STATUS_ID" NUMBER(*,0), 
	"HYVAKSYTTY_ESITYS_LAADITTU" DATE, 
	"HYVAKSYTTY_ESITYS_SAAPUNUT" DATE, 
	
	"ALOITUSKUULUTUS" DATE,
	"KOKONAISKUSTANNUKSET" FLOAT(126),
	"VALTIO" FLOAT(126), 
	
	"KUNTA" FLOAT(126), 
	
	"MUUT" FLOAT(126), 

	"INDEKSIVUOSILUKU" NUMBER(*,0), 
	"MAARAKENNUSINDEKSI" NUMBER(*,19), 
	"LAKKAAMINEN" NUMBER, 
	"KIIREELLINEN_KASITTELY" NUMBER, 
	"MUISTUTUSTEN_LUKUMAARA" NUMBER(*,0), 
	"KOHDE_ID1" NUMBER(*,0), 
	"KOHDE_ID2" NUMBER(*,0), 

	"SELITYS" VARCHAR2(1000 BYTE), 
	"HYVAKSYTTY_PAATOS_ANNETTU" DATE, 
		 
	"JATKOPAATOS_1_ANNETTU" DATE,
	"JATKOPAATOS_2_ANNETTU" DATE,
	"PALAUTETTU_ELYLLE" DATE,
	"LVM_LAADITTU" DATE, 
	"LVM_HYVAKSYMISPAATOS" DATE, 
	"LVM_JATKOPAATOS" DATE,
	"OSAPAATOS_ANNETTU" VARCHAR2(500 BYTE), 
	"VALITUSTEN_MAARA" NUMBER(*,0), 
	"HAO_VALIPAATOKSEN_PAIVAMAARA" VARCHAR2(500 BYTE), 
	"HAO_KUMOTTU" NUMBER,
	"HAO_PVM" DATE, 
	"HAO_SISALTO" VARCHAR2(1000 BYTE), 
	"KHO_VALIPAATOKSEN_PAIVAMAARA" VARCHAR2(1000 BYTE), 
	"KHO_KUMOTTU" NUMBER, 
	"KHO_PVM" DATE, 
	"KHO_SISALTO" VARCHAR2(1000 BYTE), 
	"LAINVOIMAISUUS" VARCHAR2(200 BYTE), 
	"LAINVOIMAISUUS_PAATTYY" DATE, 
	"RAUENNUT" VARCHAR2(1000 BYTE), 
	"SUUNNITELMA_LAADITTU" VARCHAR2(1000 BYTE), 
		
	"KASITTELIJA" VARCHAR2(100 BYTE), 

"HISTORIATYYPPI" VARCHAR2(6) NOT NULL,
"RIVITUNNUS" NUMBER,
"RIVITILA" VARCHAR2(15),
"RIVILUOTUPVM" TIMESTAMP (6),
"RIVIMUOKATTUPVM" TIMESTAMP (6),
"RIVIMUOKKAAJATUNNUS" VARCHAR2(150),
"DOCUMENT_ID" VARCHAR2(255),

CONSTRAINT "RT_HISTORIA" PRIMARY KEY ("RIVI_ID"));

CREATE SEQUENCE "RT_HIST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;