ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN JATKOPAATOS TO LVM_JATKOPAATOS;

ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "TS_WID" TO "TUNNUS";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "DIAARI" TO "ASIANUMERO";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "TIESUUNNITELMA_NIMI" TO "SUUNNITELMAN_NIMI";

ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "TIESUUNNITELMAN_KUVAUS" TO "SUUNNITELMAN_KUVAUS";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "TS_KOHDE_ID" TO "KOHDE_ID";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "TS_KOHDE_ID2" TO "KOHDE_ID2";

ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "HAO_PAATOKSEN_PAIVAMAARA" TO "HAO_PVM";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "HAO_PAATOKSEN_SISALTO" TO "HAO_SISALTO";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "KHO_PAATOKSEN_PAIVAMAARA" TO "KHO_PVM";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "KHO_PAATOKSEN_SISALTO" TO "KHO_SISALTO";

ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "LAINVOIMAISUUDEN_PAATTYMINEN" TO "LAINVOIMAISUUS_PAATTYY";


RENAME YLEISSUUNITELMA_SEQ TO YLEISSUUNNITELMA_SEQ;


ALTER TABLE "YLEISSUUNITELMA" RENAME TO "YLEISSUUNNITELMA";

ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN JATKOPAATOS TO LVM_JATKOPAATOS;

ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "YS_WID" TO "TUNNUS";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "DIAARI" TO "ASIANUMERO";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "Y_STATUS_ID" TO "STATUS_ID";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "YLEISSUUNNITELMAN_NIMI" TO "SUUNNITELMAN_NIMI";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "YLEISSUUNITELMAN_KUVAUS" TO "SUUNNITELMAN_KUVAUS";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "TIESUUNNITELMA_LAADITTU" TO "SUUNNITELMA_LAADITTU";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "LAINVOIMASUUS_PAATTYY" TO "LAINVOIMAISUUS_PAATTYY";


