ALTER TABLE "TIESUUNNITELMA" DROP
(
"YVA_HANKE",
"ALOITUSKUULUTUS",
"SAHKO",
"VIESTINTA",
"VESI",
"JATKOPAATOS_1_ANNETTU",
"JATKOPAATOS_2_ANNETTU",
"PALAUTETTU_ELYLLE",

"RIVILUOTUPVM",
"RIVIMUOKATTUPVM",
"RIVIMUOKKAAJATUNNUS",
"DOCUMENT_ID"
);

ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN LVM_JATKOPAATOS TO JATKOPAATOS;

ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "TUNNUS" TO "TS_WID";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "ASIANUMERO" TO "DIAARI";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "SUUNNITELMAN_NIMI" TO "TIESUUNNITELMA_NIMI";

ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "SUUNNITELMAN_KUVAUS" TO "TIESUUNNITELMAN_KUVAUS";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "KOHDE_ID" TO "TS_KOHDE_ID";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "KOHDE_ID2" TO "TS_KOHDE_ID2";

ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "HAO_PVM" TO "HAO_PAATOKSEN_PAIVAMAARA";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "HAO_SISALTO" TO "HAO_PAATOKSEN_SISALTO";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "KHO_PVM" TO "KHO_PAATOKSEN_PAIVAMAARA";
ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "KHO_SISALTO" TO "KHO_PAATOKSEN_SISALTO";

ALTER TABLE "TIESUUNNITELMA" RENAME COLUMN "LAINVOIMAISUUS_PAATTYY" TO "LAINVOIMAISUUDEN_PAATTYMINEN";



ALTER TABLE "TS_STATUS" DROP COLUMN READONLY;
DELETE FROM "TS_STATUS" WHERE "STATUS_ID" = 11;




ALTER TABLE "YLEISSUUNNITELMA" DROP
(
"YVA_HANKE",
"KOKONAISKUSTANNUKSET",
"ALOITUSKUULUTUS",
"VALTIO", 
"KUNTA", 
"MUUT", 
"SAHKO",
"VIESTINTA",
"VESI",
"INDEKSIVUOSILUKU",
"MAARAKENNUSINDEKSI", 
"MAANTIEN_LAKKAAMINEN",
"KIIREELLINEN_KASITTELY",
"MUISTUTUSTEN_LUKUMAARA",
"KOHDE_ID",
"KOHDE_ID2",
"JATKOPAATOS_1_ANNETTU",
"JATKOPAATOS_2_ANNETTU",
"PALAUTETTU_ELYLLE",
"LVM_LAADITTU",
"LVM_HYVAKSYMISPAATOS",
"HAO_VALIPAATOKSEN_PAIVAMAARA",
"HAO_KUMOTTU",
"KHO_VALIPAATOKSEN_PAIVAMAARA",
"KHO_KUMOTTU",

"RIVILUOTUPVM",
"RIVIMUOKATTUPVM",
"RIVIMUOKKAAJATUNNUS",
"DOCUMENT_ID"
);

ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN LVM_JATKOPAATOS TO JATKOPAATOS;

ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "TUNNUS" TO "YS_WID";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "ASIANUMERO" TO "DIAARI";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "STATUS_ID" TO "Y_STATUS_ID";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "SUUNNITELMAN_NIMI" TO "YLEISSUUNNITELMAN_NIMI";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "SUUNNITELMAN_KUVAUS" TO "YLEISSUUNITELMAN_KUVAUS";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "SUUNNITELMA_LAADITTU" TO "TIESUUNNITELMA_LAADITTU";
ALTER TABLE "YLEISSUUNNITELMA" RENAME COLUMN "LAINVOIMAISUUS_PAATTYY" TO "LAINVOIMASUUS_PAATTYY";

ALTER TABLE "YLEISSUUNNITELMA" RENAME TO "YLEISSUUNITELMA";


RENAME YLEISSUUNNITELMA_SEQ TO YLEISSUUNITELMA_SEQ;




ALTER TABLE YS_STATUS DROP COLUMN READONLY;

UPDATE YS_STATUS SET SELITE='Otettu hyväksymiskäsittelyyn' WHERE STATUS_ID = 2;
UPDATE YS_STATUS SET SELITE='Hyväksymispäätös annettu' WHERE STATUS_ID = 3;

DELETE FROM "YS_STATUS" WHERE "STATUS_ID"=6;
DELETE FROM "YS_STATUS" WHERE "STATUS_ID"=7;
DELETE FROM "YS_STATUS" WHERE "STATUS_ID"=9;



DROP TABLE TIESUUNNITELMAHISTORIA;
DROP SEQUENCE TIESUUNNITELMA_HIST_SEQ;



DROP TABLE YLEISSUUNNITELMAHISTORIA;
DROP SEQUENCE YLEISSUUNNITELMA_HIST_SEQ;



DROP TABLE RYS_HISTORIA;
DROP SEQUENCE RYS_HIST_SEQ;



DROP TABLE RT_HISTORIA;
DROP SEQUENCE RT_HIST_SEQ;



ALTER TABLE "YLEISSUUNITELMA" DROP COLUMN "RAUENNUT";
ALTER TABLE "TIESUUNNITELMA" DROP COLUMN "RAUENNUT";
ALTER TABLE "RAUTATIEN_YLEISSUUNNITELMA" DROP COLUMN "RAUENNUT";



ALTER TABLE "YLEISSUUNITELMA" DROP
(
	"HAO_VALIPAATOS_SISALTO",
	"KHO_VALIPAATOS_SISALTO"
);
ALTER TABLE "TIESUUNNITELMA" DROP
(
	"HAO_VALIPAATOS_SISALTO",
	"KHO_VALIPAATOS_SISALTO"
);
ALTER TABLE "RAUTATIEN_YLEISSUUNNITELMA" DROP
(
	"HAO_VALIPAATOS_SISALTO",
	"KHO_VALIPAATOS_SISALTO"
);
ALTER TABLE "RATASUUNNITELMA" DROP
(
	"HAO_VALIPAATOS_SISALTO",
	"KHO_VALIPAATOS_SISALTO"
);



DROP TABLE "DBMAINTAIN_SCRIPTS";