ALTER TABLE "TIESUUNNITELMA" ADD (
"YVA_HANKE" NUMBER,
"ALOITUSKUULUTUS" DATE,
"SAHKO" FLOAT(126),
"VIESTINTA" FLOAT(126),
"VESI" FLOAT(126),
"JATKOPAATOS_1_ANNETTU" DATE,
"JATKOPAATOS_2_ANNETTU" DATE,
"PALAUTETTU_ELYLLE" DATE,

"RIVILUOTUPVM" TIMESTAMP (6),
"RIVIMUOKATTUPVM" TIMESTAMP (6),
"RIVIMUOKKAAJATUNNUS" VARCHAR2(150),
"DOCUMENT_ID" VARCHAR2(255)
);



